### ISSUE TITLE
Разный размер AppBar'а

### ISSUE THREAD

**Issue by TheFox267** [stakancheck/ArduinoHandbookVersion2#109]
![image](https://user-images.githubusercontent.com/65784654/168439918-08e65485-7b64-4bab-9623-54abc3cafbae.png)
![image](https://user-images.githubusercontent.com/65784654/168439944-3bf5276e-a453-447b-9684-6190511a75d7.png)

**Comment by stakancheck** [comment]
посмотрим

**Comment by stakancheck** [comment]
больше не замечал такого?

**Comment by TheFox267** [comment]
Не замечал

> больше не замечал такого?
