### ISSUE TITLE
Исправить некорректное отображение при зажатии статьи (смотреть фото)

### ISSUE THREAD

**Issue by TheFox267** [stakancheck/ArduinoHandbookVersion2#22]
![IMG_20220430_175345.jpg](https://user-images.githubusercontent.com/65784654/166110605-84ba8c63-5338-4ffa-a0d0-e8bff14a0f71.jpg)
![IMG_20220430_175327.jpg](https://user-images.githubusercontent.com/65784654/166110607-c78551e9-4ff5-47c1-b5e9-80b3f6142699.jpg)

**Comment by stakancheck** [comment]
починил
