### ISSUE TITLE
Исправить поле для ввода(смотреть фото)

### ISSUE THREAD

**Issue by TheFox267** [stakancheck/ArduinoHandbookVersion2#28]
![IMG_20220501_193844.jpg](https://user-images.githubusercontent.com/65784654/166155552-e4b904d4-4219-4d9e-9b46-e7b7800786b1.jpg)

**Comment by stakancheck** [comment]
исправлено с последним пул-реквестом

**Comment by TheFox267** [comment]
Не исправлено Проверялось на последнем обновлении

**Comment by stakancheck** [comment]
ты угараешь?

**Comment by TheFox267** [comment]
Автоподстановка выводит коряво

**Comment by TheFox267** [comment]
> ты угараешь?

Нет конечно

**Comment by stakancheck** [comment]
![Screenshot_20220501-195220_Arduino HandBook.jpg](https://user-images.githubusercontent.com/49817414/166155998-9eb36c36-e906-4f1c-b680-7e825f9297e8.jpg)

**Comment by TheFox267** [comment]
Я написал, когда выходит ошибка Повторю Она выходит, когда нажимаешь на автоподстановку сохранённых данных от google

**Comment by stakancheck** [comment]
![Screenshot_20220501-195308_Arduino HandBook.jpg](https://user-images.githubusercontent.com/49817414/166156018-e5cd5dd4-a8d8-4ba9-9476-8b45140f5699.jpg)
с подстановкой

**Comment by TheFox267** [comment]
Почему пароль не подставился

**Comment by TheFox267** [comment]
https://user-images.githubusercontent.com/65784654/166156090-3d69dcb9-090d-42bb-bea7-f4436e2becc6.mp4

**Comment by stakancheck** [comment]
НеВозМоЖнО
