### ISSUE TITLE
Цвет текста не работает при просмотре статьи

### ISSUE THREAD

**Issue by TheFox267** [stakancheck/ArduinoHandbookVersion2#48]
![image](https://user-images.githubusercontent.com/65784654/167196455-6bbb71fe-0346-4aa1-ba22-e7b349bffb8b.png)
![image](https://user-images.githubusercontent.com/65784654/167196509-8d792443-0f55-48ea-a16a-82627ca3e0a9.png)

**Comment by stakancheck** [comment]
![image](https://user-images.githubusercontent.com/49817414/167312488-f2dd571f-eba3-4431-9bf9-a96cd429a9de.png)
Сделал, работает не все, но уже лучше.
В будущем стоит перейти на WebView при отображении статьи. Но это долго делать (надо подгонять шрифты и морочаться с html)
