### ISSUE TITLE
Сделать анимацию переходов медленнее

### ISSUE THREAD

**Issue by TheFox267** [stakancheck/ArduinoHandbookVersion2#62]

**Comment by TheFox267** [comment]
Сделать переход медленнее между списком категорий и списком статей. Также между списком статей и чтением статьи.
https://user-images.githubusercontent.com/65784654/167308030-20ac166b-e1a4-4362-9e8f-6c0316afcce5.mp4

**Comment by stakancheck** [comment]
Done
