### ISSUE TITLE
Заголовок залезает на кнопку (см. фото)

### ISSUE THREAD

**Issue by TheFox267** [stakancheck/ArduinoHandbookVersion2#66]

**Comment by TheFox267** [comment]
![image](https://user-images.githubusercontent.com/65784654/167409137-39f114da-c466-47da-b36b-964d96e4143a.png)

**Comment by stakancheck** [comment]
Случайно закрыл, потому что привязал ветку.
Необходимо использовать material appbar, потом посмотрим там.

**Comment by stakancheck** [comment]
![image](https://user-images.githubusercontent.com/49817414/167580506-c3a3fb7d-7d8e-4f5a-8bed-7ccd6bcd2fcb.png)
Размер теперь меняется и заголовок переносится на след. строчку
