### ISSUE TITLE
Добавить иконку удаления статьи в списке "моих статей" и связать с ней удаление статей

### ISSUE THREAD

**Issue by TheFox267** [stakancheck/ArduinoHandbookVersion2#9]
На стрелочку добавить иконку "удаления статьи"
![IMG_20220429_191103.jpg](https://user-images.githubusercontent.com/65784654/165982943-6f360c3e-c421-47de-8c94-a63ea50be7a1.jpg)

**Comment by stakancheck** [comment]
Для каждого отдельную?

**Comment by TheFox267** [comment]
Если пользователь делает длинное нажатие на элемент, то выходит диалоговое окно(я сделаю) с подтверждением удаления

**Comment by TheFox267** [comment]
Fix #42
