### ISSUE TITLE
Не удаляется пустая категория после редактирования статьи

### ISSUE THREAD

**Issue by stakancheck** [stakancheck/ArduinoHandbookVersion2#94]
При удалении статьи я реализовал проверку категории на "пустоту". После удаления вызывается проверка категории (у бывшей статьи), если она больше нигде не используется, то она удаляется из списка.
Нужно сделать тоже самое для изменения статьи.

**Comment by stakancheck** [comment]
сделаешь?

**Comment by TheFox267** [comment]
Да

**Comment by stakancheck** [comment]
В MyCategories есть в конце старый метод deleteLegacyCategories, он может тебе пригодиться. Просто размести его вызов там где нужно (после изменения статьи)
